baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

[module]
  [[module.imports]]
    path = "github.com/hugo-sid/hugo-blog-awesome"

[[params.socialIcons]]
    name = "github"
    url = "https://github.com/acakluqman"

[[params.socialIcons]]
    name = "instagram"
    url = "https://instagram.com/acakluqman_"

[params]
  goToTop = true
  toc = true

